import { LegalDocument, type LegalSection } from "@/components/marketing/legal-document";
import { CONTACT_EMAIL } from "@/lib/copy";

export const metadata = { title: "Terms of Service" };

const SECTIONS: LegalSection[] = [
  {
    heading: "These terms",
    blocks: [
      `These terms govern your use of Privett, marketing software for UK estate agents operated by Privett Ltd ("Privett", "we", "us"). By creating an account or using the service, you agree to them. If you're agreeing on behalf of an agency, you confirm you're authorised to do so.`,
    ],
  },
  {
    heading: "The service",
    blocks: [
      "Privett helps estate agents produce marketing assets, including AI-generated property descriptions, virtual staging, floor plans created from sketches, photo enhancements, and EPC lookups. We may add, change, or remove features over time.",
    ],
  },
  {
    heading: "Your account",
    blocks: [
      "You're responsible for your account, your team members' access, and keeping your login credentials secure. The service is for property professionals and you must be 18 or over to use it. Tell us promptly if you suspect any unauthorised use.",
    ],
  },
  {
    heading: "Acceptable use",
    blocks: [
      "You agree to use Privett lawfully and only for genuine property marketing. In particular, you agree not to:",
      [
        "upload content you don't have the right to use, including photographs you don't own or hold a licence for;",
        "upload unlawful, infringing, or misleading material;",
        "attempt to break, overload, reverse-engineer, or circumvent the limits of the service;",
        "use the service to process personal data of individuals without a lawful basis.",
      ],
    ],
  },
  {
    heading: "AI-generated content",
    blocks: [
      "Descriptions, staging, floor plans and enhancements are generated by AI and are provided as a starting point. They can contain errors. You are responsible for reviewing and correcting every asset before you publish or rely on it.",
      "Virtual staging and photo enhancements alter the appearance of a property. To comply with the Consumer Protection from Unfair Trading Regulations, you must clearly label virtually staged or materially enhanced images as such, and must not use them to mislead buyers or tenants about the actual condition of a property.",
    ],
  },
  {
    heading: "Plans, billing and trials",
    blocks: [
      "Paid plans are billed in advance through Stripe on a recurring basis until cancelled. Each plan includes monthly usage allowances; these reset at the start of each calendar month. Free trials convert to a paid plan unless you cancel before the trial ends.",
      "You can change or cancel your plan at any time from your account. Cancellation takes effect at the end of the current billing period. Except where required by law, fees already paid are non-refundable.",
    ],
  },
  {
    heading: "Your content and ownership",
    blocks: [
      "You keep all rights to the property content you upload and to the marketing assets you generate. You grant us a limited licence to host, process, and transmit that content to our sub-processors solely to provide the service. We own the Privett software, brand, and platform.",
    ],
  },
  {
    heading: "Data protection",
    blocks: [
      "Our handling of personal data is described in our Privacy Policy. Where we process personal data contained in your property content, we act as your processor and you act as the controller; you're responsible for having a lawful basis to upload it.",
    ],
  },
  {
    heading: "Availability and warranties",
    blocks: [
      "We work hard to keep Privett available and accurate, but the service is provided on an 'as is' and 'as available' basis. We don't warrant that it will be uninterrupted, error-free, or that AI output will be fit for a particular purpose.",
    ],
  },
  {
    heading: "Liability",
    blocks: [
      "Nothing in these terms limits liability that cannot be limited by law. Subject to that, we are not liable for indirect or consequential loss, or for loss arising from your reliance on AI-generated content, and our total liability in any 12-month period is limited to the fees you paid us in that period.",
    ],
  },
  {
    heading: "Termination",
    blocks: [
      "You can stop using Privett and close your account at any time. We may suspend or terminate access if you breach these terms or use the service in a way that risks harm to others or to the platform.",
    ],
  },
  {
    heading: "Governing law and changes",
    blocks: [
      `These terms are governed by the laws of England and Wales, and the courts of England and Wales have exclusive jurisdiction. We may update these terms from time to time; material changes will be notified and the date above updated. Questions? Email ${CONTACT_EMAIL}.`,
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      lastUpdated="10 June 2026"
      intro="These terms set out the deal between you and Privett: what you can expect from us, and what we ask of you in return."
      sections={SECTIONS}
    />
  );
}
