// Static asset builders. Everything produced here is a draft for the agent to
// review before publishing, and says so.

import type { GoogleBusinessSignal } from "../domain";
import type { RuleBranch } from "./types";

export const DRAFT_NOTE =
  "Draft generated by Privett from your data. Check every detail before publishing.";

export function buildRealEstateAgentJsonLd(branch: RuleBranch, gbp: GoogleBusinessSignal | null): string {
  const data: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "RealEstateAgent",
    name: branch.name,
    url: branch.website ?? (branch.domain ? `https://${branch.domain}` : undefined),
    areaServed: [branch.town, ...branch.areas].map((name) => ({ "@type": "Place", name })),
    address: {
      "@type": "PostalAddress",
      streetAddress: "REPLACE: street address",
      addressLocality: branch.town,
      postalCode: branch.postcode ?? "REPLACE: postcode",
      addressCountry: "GB",
    },
    telephone: "REPLACE: phone number",
  };
  if (gbp?.rating !== null && gbp?.rating !== undefined && gbp.reviewCount) {
    // Only include a rating we actually observed, from the Google profile.
    data.aggregateRating = {
      "@type": "AggregateRating",
      ratingValue: gbp.rating,
      reviewCount: gbp.reviewCount,
    };
  }
  return [
    `<!-- ${DRAFT_NOTE} Replace every REPLACE value. Paste inside <head> on your homepage and contact page. -->`,
    `<script type="application/ld+json">`,
    JSON.stringify(data, (_k, v) => (v === undefined ? undefined : v), 2),
    `</script>`,
  ].join("\n");
}

export function buildRobotsFix(raw: string | null, blocked: { bot: string; rule: string }[]): string {
  const bots = [...new Set(blocked.map((b) => b.bot))];
  const lines = [
    `# ${DRAFT_NOTE}`,
    `# Your robots.txt currently blocks: ${bots.join(", ")}.`,
    `# Remove the matching "Disallow: /" lines for these user agents, or add the`,
    `# explicit allow blocks below ABOVE any catch-all rules.`,
    "",
    ...bots.flatMap((bot) => [`User-agent: ${bot}`, "Allow: /", ""]),
  ];
  if (raw) {
    lines.push("# Lines in your current file that cause the block:");
    for (const b of blocked) lines.push(`#   ${b.rule}`);
  }
  return lines.join("\n");
}

export function buildLlmsTxt(branch: RuleBranch, crawlPages: Record<string, string | null>): string {
  const site = branch.website ?? `https://${branch.domain ?? "example.co.uk"}`;
  const links = Object.entries(crawlPages)
    .filter(([, url]) => url)
    .map(([label, url]) => `- [${label}](${url})`);
  return [
    `# ${branch.name}`,
    "",
    `> Estate and letting agent covering ${[branch.town, ...branch.areas].join(", ")}.`,
    "",
    `<!-- ${DRAFT_NOTE} Save as /llms.txt at the root of ${site}. -->`,
    "",
    "## Key pages",
    "",
    `- [Home](${site})`,
    ...links,
    "",
  ].join("\n");
}

export function buildReviewTemplates(branch: RuleBranch): string {
  return [
    `${DRAFT_NOTE}`,
    "",
    "SMS (send within a day of completion or move-in)",
    "---",
    `Hi {first name}, it was a pleasure helping with {address}. If you have a minute, a Google review helps other people in ${branch.town} find us: {review link}. Thank you, {your name} at ${branch.name}`,
    "",
    "Email",
    "---",
    `Subject: A quick favour from ${branch.name}`,
    "",
    "Hi {first name},",
    "",
    `Thank you for choosing ${branch.name}. If we did a good job, would you leave us a short Google review? It takes a minute and helps other sellers and landlords in ${branch.town} decide who to trust.`,
    "",
    "{review link}",
    "",
    "If anything could have gone better, reply to this email and I'll pick it up personally.",
    "",
    "{your name}",
    "",
    "Tips",
    "---",
    "- Ask everyone, at the same point in every sale or let, so reviews keep arriving steadily.",
    "- Never offer incentives for reviews or ask only happy clients: both break Google's policies.",
    "- Reply to every review, good or bad, within a few days.",
  ].join("\n");
}

/** Known UK directories and review sites, with listing steps. */
export const CITATION_SOURCE_GUIDES: Record<string, { label: string; steps: string[] }> = {
  "allagents.co.uk": {
    label: "allAgents",
    steps: [
      "Search for your branch on allagents.co.uk and claim the listing.",
      "Complete the profile: areas covered, fees, team.",
      "Ask recent clients to leave a review there as well as on Google.",
    ],
  },
  "getagent.co.uk": {
    label: "GetAgent",
    steps: [
      "Check your branch page on getagent.co.uk; its data comes from portal sales history.",
      "Contact GetAgent to claim the profile and correct branch details.",
    ],
  },
  "trustpilot.com": {
    label: "Trustpilot",
    steps: [
      "Claim your free Trustpilot business profile.",
      "Add the Trustpilot review link to your post-completion emails.",
    ],
  },
  "rightmove.co.uk": {
    label: "Rightmove",
    steps: [
      "Check your branch profile on Rightmove is complete, with a description naming the areas you cover.",
      "Keep listings current: AI answers cite branch pages with active stock.",
    ],
  },
  "zoopla.co.uk": {
    label: "Zoopla",
    steps: ["Complete your Zoopla agent profile, including the areas you cover and a branch description."],
  },
  "yell.com": {
    label: "Yell",
    steps: ["Claim and complete your free Yell listing with consistent name, address and phone number."],
  },
  "thinkproperty.co.uk": {
    label: "ThinkProperty",
    steps: ["Check for an existing listing and request it is claimed or added."],
  },
};
