import type { GoogleBusinessSignal, IntentGroup, WebsiteCrawlSignal } from "../domain";

export interface RuleBranch {
  id: string;
  name: string;
  domain: string | null;
  website: string | null;
  town: string;
  areas: string[];
  postcode: string | null;
}

export interface RuleCompetitor {
  id: string;
  name: string;
  domain: string | null;
  /** Visibility % of this competitor over the same responses, null if unknown. */
  visibility: number | null;
  gbp: GoogleBusinessSignal | null;
  crawl: WebsiteCrawlSignal | null;
}

export interface RulePromptStat {
  text: string;
  intentGroup: IntentGroup;
  area: string | null;
  responses: number;
  visibility: number | null;
  /** Agents most often named instead, by name. */
  namedInstead: string[];
}

export interface RuleCitationStat {
  domain: string;
  /** Responses citing this domain. */
  responses: number;
  citesBranch: boolean;
  /** Competitors whose pages on this domain were cited, or who were named alongside it. */
  competitorsCited: string[];
}

export interface RuleContext {
  branch: RuleBranch;
  crawl: WebsiteCrawlSignal | null;
  gbp: GoogleBusinessSignal | null;
  /** The competitors AI recommends most (top by visibility), max ~5. */
  topCompetitors: RuleCompetitor[];
  prompts: RulePromptStat[];
  citations: RuleCitationStat[];
  branchVisibility: number | null;
  totalResponses: number;
}

export type AssetKind =
  | "json-ld"
  | "robots"
  | "faq"
  | "area-page"
  | "review-templates"
  | "llms-txt"
  | "steps"
  | "valuation-page";

export interface RecommendationDraft {
  ruleId: string;
  ruleVersion: number;
  /** Stable per branch: rule id plus whatever makes this instance unique. */
  fingerprint: string;
  title: string;
  /** Plain-English reason, citing the actual numbers. */
  why: string;
  priority: 1 | 2 | 3 | 4 | 5;
  effort: "S" | "M" | "L";
  evidence: Record<string, unknown>;
  asset:
    | { kind: AssetKind; text: string }
    /** Asset to be generated by the worker with the Anthropic API. */
    | { kind: AssetKind; generate: { instructions: string; input: Record<string, unknown> } }
    | null;
}

export interface Rule {
  id: string;
  version: number;
  description: string;
  evaluate(ctx: RuleContext): RecommendationDraft[];
}
